name: Go

on:
  push:
    branches: [ "2.0-oci-support" ]
  pull_request:
    branches: [ "2.0-oci-support" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: registry.vanillaos.org/vanillaos/pico:main
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install build dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libbtrfs-dev libdevmapper-dev libgpgme-dev pkg-config build-essential

    - name: Build
      run: go build -o abrootv2

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "continuous"
        prerelease: true
        title: "Continuous Build"
        files: |
          abrootv2
